### ISSUE TITLE
[Bug] Can't enter the service name to connect to containerized backend via Docker

### ISSUE THREAD

**Issue by wbste** [phidatahq/phidata#3682]
### Description

Trying to "dockerize" the front end and back end. I can't enter the container name (`http://backend:7777`), and the internal IP of the container changes at times. (I also get CORS errors but need to test a few other things, as it works if the BE is running on the host in python, but NOT if it's containerized).

Both FE and BE are in the same stack.

In the self-hosted playground, when I enter `http://backend:7777`, I get "Please enter a valid URL".

### Steps to Reproduce

Build **backend**:

```
# --- Build Stage ---
    FROM python:3.13-alpine AS builder

    # Set working directory
    WORKDIR /app
    
    # Install build dependencies
    RUN apk add --no-cache \
        gcc \
        musl-dev \
        libffi-dev \
        openssl-dev \
        python3-dev \
        cargo
    
    # Copy and install dependencies
    COPY requirements.txt .
    RUN pip install --no-cache-dir --upgrade pip && \
        pip install --no-cache-dir --prefix=/install -r requirements.txt
    
    # --- Final Stage ---
    FROM python:3.13-alpine
    
    # Set working directory
    WORKDIR /app
    
    # Install runtime dependencies (only necessary libraries)
    RUN apk add --no-cache libffi openssl
    
    # Copy installed dependencies from the builder stage
    COPY --from=builder /install /usr/local
    
    # Copy application files
    COPY . .
    
    # Expose port
    EXPOSE 7777
    
    # Run server
    CMD ["python", "main.py"]
```

Build **frontend**:

```
FROM node:20-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apk --no-cache add git
RUN corepack enable
RUN git clone https://github.com/agno-agi/agent-ui.git /app
WORKDIR /app

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=build /app/.next /app/.next
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/next.config.ts /app/next.config.ts
EXPOSE 8000
CMD ["node_modules/.bin/next", "start", "-p", "8000", "-H", "0.0.0.0"]
```

Run with compose

```yml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3007:8000
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./storage:/app/storage
      - ./scripts:/app/scripts
```

### Expected Behavior

"regular" URLs work.

### Actual Behavior

"regular" URLs don't work. 😢 

### Environment

```markdown
- Windows 11 Pro
- Firefox and Edge
- Latest version of FE and BE as of this date.
```
