### ISSUE TITLE
[Feature Request] t2v-transformers (embedder) which can natively be configured for Weaviate vector_db does not seem to be supported.

### ISSUE THREAD

**Issue by Siete-F** [phidatahq/phidata#3684]
### Problem Description

This embedder can be started in docker next to the vector db. Queries can then be send directly to the Weaviate vector db and will be converted to vectors inside the database itself.
I tried but couldn't make Agno use the already configured embedder, you will always have to use a local custom embedder. Also, when trying to access the docker hosted t2v-transformers from Agno directly, I couldn't get it to work. Maybe I missed something there?

Code I used for docker-compose:
https://weaviate.io/developers/weaviate/installation/docker-compose#weaviate-with-the-text2vec-transformers-module

### Proposed Solution

For Weaviate vector_db, enable the "special" t2v-transformers

OR

Support docker hosted embedders.

### Alternatives Considered

In Agno I used "huggingFace" and "SentenceTransformers", but that is simply because I didn't understand how this connection to a locally docker hosted embedder could be done.
Is this supported?
If no, can that be supported?

### Additional Context

Windows, Docker hosted vector db and embedder, Gemini Flash 2.0, Agno 1.6.3

### Would you like to work on this?

- [ ] Yes, I’d love to work on it!
- [x] I’m open to collaborating but need guidance.
- [ ] No, I’m just sharing the idea.

**Comment by Siete-F** [comment]
Docker compose file

```yml
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.3
    restart: on-failure:0
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate_vec_db:/var/lib/weaviate

  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA
```
